racy_feature_more =
    EXTRACT murl,
            purl,
            label,
            DocKey,
            Vector,
            TenantId
    FROM "/shares/SegmentRelevance/SegmentRelevance/Prod/Image/SparkSchedulingSupport/Prism/HitApp/RacyFeature/2022_06_27/racy_feature_more.tsv"
    USING Extractors.Tsv();

racy_feature_more =
    SELECT *,
           Convert.ToDateTime("6/27/2022 1:59:32 PM") AS Date
    FROM racy_feature_more;

OUTPUT racy_feature_more
TO "/shares/SegmentRelevance/SegmentRelevance/Prod/Image/SparkSchedulingSupport/Prism/HitApp/RacyFeature/2022_07_07/racy_feature_more.tsv"
USING DefaultTextOutputter(outputHeader: true);