REFERENCE @"/shares/MMRepository.prod/MMRepository/Prod/Image/Repository/Binaries/MMRV2.ScheduleSelection.dll";
REFERENCE "/shares/SegmentRelevance/SegmentRelevance/Reco/Resources/Microsoft.Bing.HashUtil.dll";
REFERENCE "/shares/MMRepository.prod/MMRepository/Prod/Image/Repository/Binaries/MMRV2.Core.dll";
REFERENCE "/shares/MMRepository.prod/MMRepository/Prod/Image/Repository/Binaries/MMRV2.SnapshotMerger.dll";
REFERENCE "/shares/MMRepository.prod/MMRepository/Prod/Image/Repository/Binaries/MMRV2.Utility.dll";
RESOURCE  "/shares/MMRepository.prod/MMRepository/Prod/Image/Repository/Binaries/HashValue.dll";
REFERENCE "/shares/SegmentRelevance/SegmentRelevance/MMShared/bin/Relevance.ScopeLib.dll";
RESOURCE  "/shares/SegmentRelevance/SegmentRelevance/MMShared/bin/Relevance.ScopeLib.pdb",
          "/shares/SegmentRelevance/SegmentRelevance/MMShared/bin/Relevance.ScopeLib.xml";
REFERENCE @"D:\Data\MMCB\MMRV2\ProdCo3C\Image\Binaries\searchIndexDiscoverySelection.Prod\URLRepositoryV2Snapshots\CMPRK-Prod2-Ch1\DiscoverySelection.Shared.dll";
REFERENCE @"D:\Data\MMCB\MMRV2\ProdCo3C\Image\Binaries\searchIndexDiscoverySelection.Prod\URLRepositoryV2Snapshots\CMPRK-Prod2-Ch1\DiscoverySelection.Util.dll";
RESOURCE @"D:\data\MMCB\MMRV2\ProdCo3C\Image\Binaries\searchIndexDiscoverySelection.Prod\URLRepositoryV2Snapshots\CMPRK-Prod2-Ch1\tld.txt";

#DECLARE Date string = "2026_08_06";
#DECLARE In_Training_data        string = "/local/users/v-yangtian/L1/training_data/Union_UrlHash16B.ss";
#DECLARE In_IDF               string = "/local/Prod/Image/Repository/Snapshot/IDF-FluidImagePrototype/IDF/" + @Date + "/RawImageIDF.ss";
#DECLARE In_NoduleRank        string = "/local/Prod/Image/Selection/AfterCrawlSelectionV4.3/2026_08_10/NoduleRankFile_Unified.ss";
#DECLARE Output_Folder        string = "/local/users/v-yangtian/OpenL1/"+ @Date + "/IDF/";
#DECLARE Output_Stats_Folder        string = "/local/users/v-yangtian/OpenL1/"+ @Date + "/stats/";

Training_data =
    SELECT *
    FROM (SSTREAM @In_Training_data);

IDF =
    SELECT Key,
           PageKey,
           IDFBlob
    FROM (SSTREAM @In_IDF);

NoduleRank =
    SELECT Key,
           PKey,
           MUrl,
           PUrl,
           AdjustedRank
    FROM (SSTREAM @In_NoduleRank);


IDF_TotalCount_Before=
    SELECT COUNT(*) AS TotalCount
    FROM IDF;

OUTPUT IDF_TotalCount_Before
TO SSTREAM @Output_Stats_Folder + "IDF_TotalCount_Before.ss";

IDF_NoduleRank =
    SELECT I.Key,
           I.PageKey AS PKey,
           I.IDFBlob,
           NR.MUrl,
           NR.PUrl,
           NR.AdjustedRank AS StaticRank
    FROM IDF AS I
         INNER JOIN NoduleRank AS NR
             ON I.Key == NR.Key AND I.PageKey == NR.PKey;

IDF_TotalCount_After=
    SELECT COUNT(*) AS TotalCount
    FROM IDF_NoduleRank;

OUTPUT IDF_TotalCount_After
TO SSTREAM @Output_Stats_Folder + "IDF_TotalCount_After.ss";


IDF_NoduleRank =
    SELECT Key,
           PKey,
           FIRST(StaticRank) AS StaticRank,
           FIRST(IDFBlob) AS IDFBlob,
           FIRST(MUrl) AS MUrl,
           FIRST(PUrl) AS PUrl
    FROM IDF_NoduleRank
    GROUP BY Key, PKey;

IDF_NoduleRank =
 SELECT Key, 
        PKey,
        StaticRank,
        IDFBlob, 
        MUrl,
        PUrl,
        GetCombinedHash(MUrl, PUrl) AS UrlHash16B 
        FROM IDF_NoduleRank;

OUTPUT IDF_NoduleRank
TO SSTREAM @Output_Folder + "IDF_NoduleRank.ss";


UrlHashMatchResult =
    SELECT UU.TypeName,
           UU.UrlHash16B,
           INR.Key,
           INR.PKey,
           INR.MUrl,
           INR.PUrl,
           INR.IDFBlob,
           INR.StaticRank,
           IF(INR.UrlHash16B == null, "Unmatched", "Matched") AS MatchStatus
    FROM Training_data AS UU
         LEFT JOIN IDF_NoduleRank AS INR
             ON UU.UrlHash16B == INR.UrlHash16B;

Matched_Training_Nodule=
    SELECT *
    FROM UrlHashMatchResult
    WHERE MatchStatus == "Matched";

OUTPUT Matched_Training_Nodule
TO SSTREAM  @Output_Folder + "Matched_Training_Nodule.ss";

UrlHashMatchResult_TypeCounts =
    SELECT TypeName,
           COUNT() AS TotalCount,
           COUNTIF(MatchStatus == "Matched") AS MatchedCount,
           COUNTIF(MatchStatus == "Unmatched") AS UnmatchedCount
    FROM UrlHashMatchResult
    GROUP BY TypeName;

UrlHashMatchResult_TypeStats =
    SELECT TypeName,
           TotalCount,
           MatchedCount,
           UnmatchedCount,
           MatchedCount * 1.0 / TotalCount AS MatchedPercentage,
           UnmatchedCount * 1.0 / TotalCount AS UnmatchedPercentage
    FROM UrlHashMatchResult_TypeCounts;

OUTPUT UrlHashMatchResult_TypeStats
TO SSTREAM @Output_Stats_Folder + "UrlHashMatchResult_TypeStats.ss";

#CS
using Microsoft.SCOPE.Types;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using ScopeRuntime;
using Microsoft.Bing.HashUtil;

public static string GetCombinedHash(string mUrl, string pUrl)
{
    string mKey = HutHash.GetUrlHashAsBase64String(mUrl);
    string pKey = HutHash.GetUrlHashAsBase64String(pUrl);
    byte[] bCodes = HutHash.GetHashAsBinary(mKey + pKey);
    return string.Concat(bCodes.Select(b => b.ToString("X2")));
}

#ENDCS
