
#DECLARE Date string = "2026_08_09";
#DECLARE In_IDF               string = "/local/Prod/Image/Repository/Snapshot/IDF-FluidImagePrototype/IDF/" + @Date + "/RawImageIDF.ss";
#DECLARE In_NoduleRank        string = "/local/Prod/Image/Selection/AfterCrawlSelectionV4.3/2026_08_10/NoduleRankFile_Unified.ss";
#DECLARE Output_Folder        string = "/local/users/v-yangtian/OpenL1/"+ @Date + "/IDF/";

IDF =
    SELECT Key,
           PageKey,
           IDFBlob
    FROM (SSTREAM @In_IDF);

NoduleRank =
    SELECT Key,
           PKey,
           MUrl,
           PUrl,
           AdjustedRank
    FROM (SSTREAM @In_NoduleRank);



IDF_NoduleRank =
    SELECT I.Key,
           I.PageKey AS PKey,
           I.IDFBlob,
           NR.MUrl,
           NR.PUrl,
           NR.AdjustedRank AS StaticRank
    FROM IDF AS I
         INNER JOIN NoduleRank AS NR
             ON I.Key == NR.Key AND I.PageKey == NR.PKey;


IDF_NoduleRank =
    SELECT Key,
           PKey,
           FIRST(StaticRank) AS StaticRank,
           FIRST(IDFBlob) AS IDFBlob,
           FIRST(MUrl) AS MUrl,
           FIRST(PUrl) AS PUrl
    FROM IDF_NoduleRank
    GROUP BY Key, PKey;



