// Copyright (C) Microsoft Corporation. All rights reserved.
// Script GUID:d43af1e8-0c68-47f1-8a69-c3f0d77031a9
// Used for tracking history


OldAttractiveV3Sensor =
    SELECT *
    FROM
    (
        SSTREAM "/local/Prod/Image/Repository/Sensor/Other/2024_12_19/AttractiveV3Sensor.ss"
    );


NewAttractiveV3Sensor =
    SELECT *
    FROM
    (
        SSTREAM "/local/users/v-yangtian/2024_12_19/AttractiveV3Sensor.ss"
    );

result =
    SELECT COUNT( * ) AS Count
    FROM OldAttractiveV3Sensor

    UNION ALL
    SELECT COUNT( * ) AS Count
    FROM NewAttractiveV3Sensor;


OUTPUT TO SSTREAM "/local/users/v-yangtian/2024_12_19/CountResult.ss";

