REFERENCE "/local/users/v-yangtian/Microsoft.ML.OnnxRuntime.dll";
REFERENCE "/local/users/v-yangtian/System.Buffers.dll";
REFERENCE "/local/users/v-yangtian/System.Memory.dll";
REFERENCE "/local/users/v-yangtian/System.Numerics.Vectors.dll";
REFERENCE "/local/users/v-yangtian/System.Runtime.CompilerServices.Unsafe.dll";
REFERENCE "/local/users/v-yangtian/XCProcessor.dll";
RESOURCE "/local/users/v-yangtian/onnxruntime.dll";

RESOURCE "/local/users/jichen4/XC/Models/1Encoder2HeadsDocLabel/onnx/query_Ret/classifier.onnx";


ImageFeatLabel =
    EXTRACT Key : string,
            NGrams : string,
            ImgEmbedding : string,
            MUrlWords : string,
            Alt : string,
            Title : string,
            PUrlWords : string,
            _filenum : int
    FROM "/local/users/jichen4/XC/Google/2023-10-18_2024-10-23/Clicked/Balance/Split/SIEMV3_D32_ImgText/val/ImageFeatLabel_{_filenum}.tsv"
    USING Extractors.Tsv(skipFirstNRows: 1);

ImageFeatLabel =
    SELECT Key,
           FIRST(NGrams) AS NGrams,
           FIRST(ImgEmbedding) AS ImgEmbedding,
           FIRST(MUrlWords) AS MUrlWords,
           FIRST(Alt) AS Alt,
           FIRST(Title) AS Title,
           FIRST(PUrlWords) AS PUrlWords
    FROM ImageFeatLabel
    WHERE (_filenum >= 0)
          AND (_filenum <= 10)
    GROUP BY Key;

result =
    PROCESS ImageFeatLabel
    USING Microsoft.Bing.ImageIndexQuality.OnnxRunner.DocProcessor("classifier.onnx", "16");


OUTPUT
TO "/local/users/jichen4/XC/Models/1Encoder2HeadsDocLabel/onnx/query_Ret/val_xc_query_embedding_csharp.tsv"
USING DefaultTextOutputter(outputHeader: true);
